version: '3.7'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: polyminder
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: /home/antrieu/data  # Path on the host machine
        target: /var/lib/postgresql/data  # Path in the container

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    
volumes: {}

